name: "Labeling by Gemini"
description: "Puts labels to Issues"

branding:
  color: blue
  icon: tag

inputs:
  gemini-api-key: # id of input
    description: "Gemini API Key"
    required: true
  github-token:
    description: "GITHUB_TOKEN"
    required: true
    default: ${{ github.token }}

runs:
  using: "node16"
  main: dist/index.js
