on:
  issues:
    types: [opened, edited]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: shbhom/labeling-by-gemini@main
        with:
          openai-api-key: ${{ secrets.GEMINI_API_KEY }}
