on:
  issues:
    types: [opened, edited]

jobs:
  test:
    runs-on: ubuntu-latest
    # env:
    #   GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    #   GITHUB_TOKEN: ${{ github.token }}

    steps:
      - uses: shbhom/labeling-by-gemini@main
        with:
          gemini-api-key: ${{ secrets.GEMINI_API_KEY }}
